### ISSUE TITLE
error for evaluation

### ISSUE THREAD

**Issue by litingsjj** [DanielMing123/InverseMatrixVT3D#1]
hi, it's a great work!
i got an error, when i run `bash tools/dist_test.sh configs/InverseMatrixVT3D_200_200_16.py InverseMatrixVT3D_200.pth 8`

 
`NotImplementedError: Could not run 'aten::sum.IntList_out' with arguments from the 'SparseCUDA' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using cu                  stom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'aten::sum.IntList_out' is only available for these backends: [Dense, FPGA, Conjugate, UNKNOWN_TENSOR_TYPE                  _ID, QuantizedXPU, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, SparseCPU, SparseCUDA, SparseHIP, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_                  ID, SparseXPU, UNKNOWN_TENSOR_TYPE_ID, SparseVE, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, NestedTensorCUDA, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOW                  N_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID].`

**Comment by DanielMing123** [comment]
Please use the latest pytorch, at least the pytorch version should be > 2.0.0 to support sparse matrix multiplication.

**Comment by litingsjj** [comment]
Got it！
here is my result, the miou is different from yours
InverseMatrixVT3D_200.pth:
`02/08 18:44:31 - mmengine - INFO - Epoch(test) [753/753]    noise: nan  barrier: 0.1902  bicycle: 0.1439  bus: 0.4121  car: 0.4006  construction_vehicle: 0.1298  motorcycle: 0.2227  pedestrian: 0.1982  traffic_cone: 0.1233  trailer: 0.1877  truck: 0.3154  driveable_surface: 0.4026  other_flat: 0.1491  sidewalk: 0.1972  terrain: 0.2272  manmade: 0.1661  vegetation: 0.2890  miou: 0.2347  acc: 0.2999  acc_cls: 0.2888  data_time: 0.0061  time: 0.3000`
InverseMatrixVT3D_256.pth:
`02/08 18:55:23 - mmengine - INFO - Epoch(test) [753/753]    noise: nan  barrier: 0.2065  bicycle: 0.1313  bus: 0.4340  car: 0.3646  construction_vehicle: 0.1319  motorcycle: 0.2254  pedestrian: 0.2064  traffic_cone: 0.1162  trailer: 0.2377  truck: 0.3468  driveable_surface: 0.3475  other_flat: 0.1390  sidewalk: 0.2060  terrain: 0.2075  manmade: 0.1659  vegetation: 0.2632  miou: 0.2331  acc: 0.2747  acc_cls: 0.2959  data_time: 0.0057  time: 0.3710`

**Comment by DanielMing123** [comment]
please try set the enable_fix=False or Ture during test, the released code has been modified a lot but the ckpt files are old. You can also try train from scratch, the best performance (mIoU goes to 26%) achieved after around 4 epoches.

**Comment by DanielMing123** [comment]
Please set enable_fix=False in each config file and try testing the model again.

**Comment by litingsjj** [comment]
Solved it with enable_fix=False
