### ISSUE TITLE
The code for OccFusion

### ISSUE THREAD

**Issue by ZYang2077** [DanielMing123/InverseMatrixVT3D#4]
Hey there, I've been working on multimodal-related task recently and I'm really interested in OccFusion. I noticed that the code link for OccFusion is no longer accessible, any plans to open-source it in the future?

**Comment by DanielMing123** [comment]
Hi, thanks for your interest, I haven't released the OccFusion code yet because the paper is still under revision and review, I will release the code after the paper is accepted

**Comment by ZYang2077** [comment]
@DanielMing123 Sorry to bother again. May I ask in your work of occfusion, are the input resolutions of images all 1600x900 in the results of the nuscenes-based occ dataset? It's not mentioned in the paper.

**Comment by DanielMing123** [comment]
The input image resolutions are all 1600*900 in all experiment results.

**Comment by noahstudyer** [comment]
Hello, have you reproduced the author's work? Where is the weight of the reasoning process @AlphaPlusTT

**Comment by ZYang2077** [comment]
@noahstudyer I did not reproduce the author's work. The reason I asked the question is to facilitate comparison with our work.
